version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: doggyclub_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: doggyclub
      POSTGRES_PASSWORD: doggyclub_dev
      POSTGRES_DB: doggyclub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doggyclub"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: doggyclub_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: